<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="agencyTest.AgencyTest" duration-ms="37811" started-at="2017-10-30T11:44:38Z" finished-at="2017-10-30T11:45:16Z">
    <groups>
    </groups>
    <test name="Command line test" duration-ms="37811" started-at="2017-10-30T11:44:38Z" finished-at="2017-10-30T11:45:16Z">
      <class name="agencyTest.AgencyTest">
        <test-method status="PASS" signature="configBeforClass()[pri:0, instance:agencyTest.AgencyTest@42d3bd8b]" name="configBeforClass" is-config="true" duration-ms="3426" started-at="2017-10-30T06:44:38Z" finished-at="2017-10-30T06:44:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configBeforClass -->
        <test-method status="PASS" signature="configBeforeMtd()[pri:0, instance:agencyTest.AgencyTest@42d3bd8b]" name="configBeforeMtd" is-config="true" duration-ms="17837" started-at="2017-10-30T06:44:42Z" finished-at="2017-10-30T06:44:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configBeforeMtd -->
        <test-method status="FAIL" signature="PatientCreate()[pri:0, instance:agencyTest.AgencyTest@42d3bd8b]" name="PatientCreate" duration-ms="14701" started-at="2017-10-30T06:44:59Z" finished-at="2017-10-30T06:45:14Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at agencyTest.AgencyTest.PatientCreate(AgencyTest.java:154)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:110)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- PatientCreate -->
        <test-method status="PASS" signature="configAfterMtd()[pri:0, instance:agencyTest.AgencyTest@42d3bd8b]" name="configAfterMtd" is-config="true" duration-ms="1109" started-at="2017-10-30T06:45:14Z" finished-at="2017-10-30T06:45:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configAfterMtd -->
        <test-method status="PASS" signature="configAfterClass()[pri:0, instance:agencyTest.AgencyTest@42d3bd8b]" name="configAfterClass" is-config="true" duration-ms="718" started-at="2017-10-30T06:45:15Z" finished-at="2017-10-30T06:45:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configAfterClass -->
      </class> <!-- agencyTest.AgencyTest -->
    </test> <!-- Command line test -->
  </suite> <!-- agencyTest.AgencyTest -->
</testng-results>
